#!/bin/bash
# a script generator
# scriptgen filename [language] [description]
# ex: scriptgen pyscript python my first script

# config 
# ----------------------------------------------------------------------
dir="$HOME/.local/bin"
editor=$EDITOR
author="belka"
github="github.com/belkadev"
# ----------------------------------------------------------------------


if [[ -z "$@" ]]; then
    echo -e "Error: enter a script name"
    exit 1;
fi
lang="bash" #default
file="$dir/$1"
name="$1"
if [[ ! -z "$2" ]]; then
lang="$2"
if [[ ! -z "$3" ]]; then
	shift;shift
	description="$@"
fi
fi
if [[ ! -f $file ]]; then
echo "#!/usr/bin/env" $lang > $file  
echo "" >> $file
echo "# ----------------------------------------------------------------------" >> $file
echo "# Date:" $(date +'%m/%d/%Y')   >> $file
echo "# Name: " $name >> $file
echo "# Author:" $author >> $file
echo "# Description: "$description >> $file
echo "# Requires: " - >> $file
echo "# Github: " $github >> $file
echo "# ----------------------------------------------------------------------" >> $file
    chmod +x $file
    notify-send "New $lang file generated."
fi
eval $editor $file
